### ISSUE TITLE
Racing app

### ISSUE THREAD

**Issue by mallowPallow** [jnccloud/Renewed-Phone-Wahyu-Abi#1]
Good day

Amazing release, thank you for it and thank the developer

Got an issue with the racing app, once you click on cancel then go to leaderboards, you're stuck there until you restart the phone or restart your game.
![image](https://github.com/jnccloud/Renewed-Phone-Wahyu-Adi/assets/131043006/1494cf9c-5101-4ed0-a6d6-cac2ab201700)

**Comment by SubZon3** [comment]
same issue with me but when i press something it still does it . shouldnt the phone disable what you do on keyboard except wsad and shift?

**Comment by jnccloud** [comment]
I do not support this script. I only shared it because of resellers reselling a free script from Renewed-Scripts. Go to the official repo for support.
